### ISSUE TITLE
outdated Delphes config in the tutorial ?

### ISSUE THREAD

**Issue by jandrea** [HEP-FCC/fcc-tutorials#55]
Hi All,

following the fastsim tutorial, 

https://hep-fcc.github.io/fcc-tutorials/fast-sim-and-analysis/FccFastSimAnalysis.html

The propose delphes configuration on the page seem to miss the line:
muonSaveTool.saveTrkCov = True

that is needed for the analysis script to run.

Also, the example does not match the config that is in the file: 
https://github.com/HEP-FCC/FCCSW/blob/master/Sim/SimDelphesInterface/options/PythiaDelphes_config_IDEAtrkCov.py

Cheers,
Jeremy

**Comment by vvolkl** [comment]
Hi @jandrea, thanks! I guess you meant the page https://hep-fcc.github.io/fcc-tutorials/fast-sim-and-analysis/FccFastSimDelphes.html, the one you linked doesn't have any delphes configuration. Fixed it - the switch to the key4hep/edm4hep based components is now imminent, so I'll go through this again when I'm done there.
